name: Build tensorflow for specific architectures

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published, created]

jobs:
  build-tensorflow:
    runs-on: ubuntu-latest

    name: Build tensorflow-v2.5.0-${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch:
          - nehalem
          - silvermont
          - skylake
          - skylake-avx512
          - broadwell
          - westmere
          - haswell
          - bonnell

    container:
      image: tensorflow/tensorflow:devel

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Run build
        shell: bash
        env:
          march: ${{ matrix.arch }}
          mtune: ${{ matrix.arch }}
          tensorflowversion: v2.5.0
        run: |
          export bazel_output_base="$(pwd)/bazel"
          mkdir -p $bazel_output_base
          cd repo
          ./build_tensorflow_architecture.sh 

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          path: bazel/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/libtensorflow*
          name: libtensorflow-v2.5.0-${{matrix.arch}}
