name: Build tensorflow for specific architectures

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published, created]

jobs:
  build-tensorflow:
    runs-on: ubuntu-latest

    name: Build tensorflow-v2.5.0-${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch:
          - nehalem
          - silvermont
          - skylake
          - skylake-avx512
          - broadwell
          - westmere
          - haswell
          - bonnell

    container:
      image: tensorflow/tensorflow:devel

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
      
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run build
        shell: bash
        env:
          march: ${{ matrix.arch }}
          mtune: ${{ matrix.arch }}
          tensorflowversion: ${{matrix.version}}
        run: |
          export bazel_output_base="$(pwd)/bazel"
          mkdir -p $bazel_output_base
          cd repo
          ./build_tensorflow_architecture.sh

      - name: Zip build
        shell: bash
        run: |
          tar -czf libtensorflow.tar.gz bazel/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/libtensorflow*

      - run:   |
               upload_url=$(curl -sL https://api.github.com/repos/marcelklehr/build_tensorflow/releases | jq '. | map(select(.tag_name == "${{matrix.version}}")) [0].upload_url')
               echo UPLOAD_URL=$upload_url >> $GITHUB_ENV
        shell: bash

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./libtensorflow.tar.gz
          asset_name: libtensorflow-${{matrix.version}}-${{matrix.arch}}.tar.gz
          asset_content_type: application/gzip
