name: Build tensorflow

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published, created]

jobs:
  build-tensorflow:
    runs-on: ubuntu-latest

    name: Build tensorflow

    container:
      image: tensorflow/tensorflow:devel

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: git-tree

      - name: Run all builds
        shell: bash
        run: |
          cd git-tree
          ./run_all_builds.sh

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          path: git-tree/bazel/*/
