name: Build tensorflow

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published, created]

jobs:
  build-tensorflow:
    runs-on: ubuntu-latest

    name: Build tensorflow-v2.5.0-${{ matrix.opt }}

    strategy:
      fail-fast: false
      matrix:
        opt:
          - mkl_only
          - nothing
          - O3_only
          - AVX2_only
          - mkl_AVX2_only
          - mkl_O3_only
          - nothingOs

    container:
      image: tensorflow/tensorflow:devel

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Run all builds
        shell: bash
        env:
          opt: ${{ matrix.opt }}
          tensorflowversion: v2.5.0
        run: |
          export bazel_output_base="$(pwd)/bazel"
          mkdir -p $bazel_output_base
          cd repo
          ./build_tensorflow_instructionsets.sh 

      - name: Zip result
        shell: bash
        run: |
          ls bazel
          tar -cf build.tar bazel

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          path: build.tar
          name: libtensorflow-v2.5.0-${{matrix.opt}}
